import sys
import unittest
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.models.core_models import Repo, Project, Application  # noqa: E402


class TestModelsValidation(unittest.TestCase):
    def test_repo_url_must_be_valid(self):
        with self.assertRaises(Exception):
            Repo(repo_url="not-a-url", repo_branch="main")

    def test_repo_branch_max_length(self):
        long_branch = "a" * 51
        with self.assertRaises(Exception):
            Repo(repo_url="https://example.com/repo.git", repo_branch=long_branch)

    def test_project_id_auto_uuid(self):
        project = Project(name="Proj")
        # id se genera, y debe ser UUID4 válido
        uuid.UUID(project.id, version=4)

    def test_application_requires_uuid_project(self):
        with self.assertRaises(Exception):
            Application(project_id="invalid", name="App")

    def test_application_id_autogenerated(self):
        app = Application(project_id=str(uuid.uuid4()), name="App")
        uuid.UUID(app.id, version=4)


if __name__ == "__main__":
    unittest.main()
